---
abstract: 'collection of blocks parametrized by language and language independent'
author:
  - 'Treex team <treex@ufal.mff.cuni.cz>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Test::More: 0
  Test::Output: 0
  Treex::Core::Config: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Treex-Unilang
requires:
  File::Slurp: 0
  Moose: 0
  Treex::Core::Block: 0
  Treex::Core::Common: 0
  Treex::Core::Document: 0
  Treex::Core::DocumentReader: 0
  utf8: 0
version: 0.06903_1
