---
abstract: 'collection of blocks parametrized by language and language independent'
author:
  - 'Treex team <treex@ufal.mff.cuni.cz>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Test::More: 0
  Test::Output: 0
  Test::Requires: 0
  Treex::Core::Config: 0
  perl: 5.006
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Treex-Unilang
requires:
  File::Slurp: 0
  Moose: 0
  Treex::Block::Read::BaseTextReader: 0
  Treex::Block::W2A::AnalysisWithAlignedTrees: 0
  Treex::Block::Write::BaseTextWriter: 0
  Treex::Core: 0.08051
  Treex::Core::Block: 0
  Treex::Core::Common: 0
  Treex::Core::Document: 0
  Treex::Core::DocumentReader: 0
  Treex::Core::Resource: 0
  Treex::Tool::Parser::MSTperl::Config: 0
  Treex::Tool::Parser::MSTperl::Node: 0
  Treex::Tool::Parser::MSTperl::Parser: 0
  Treex::Tool::Parser::MSTperl::Sentence: 0
  strict: 0
  utf8: 0
  warnings: 0
version: 0.08055
